### ISSUE TITLE
Switch to Matic

### ISSUE THREAD

**Issue by CertDigital** [Kredeum/gr9#1]
Say switch to matic now under media in the mint column. Also says say same thing when you click on nfts Kredeum plugin

![matic_message2](https://user-images.githubusercontent.com/35381679/113908799-f07bad80-97a4-11eb-9017-833cd777f567.PNG)
![matic_message1](https://user-images.githubusercontent.com/35381679/113908824-f96c7f00-97a4-11eb-9c20-571a3014afc1.PNG)

**Comment by zapaz** [comment]
Yes not explicit:  you have to change the network to Matic/Polygon inside Metamask , in order to Mint NFT on Polygon

1. Some user documentation has to be made, to be more explicit... 
2. Also one popup to add, to propose automatic network configuration in Metamask for Polygon

**Comment by zapaz** [comment]
Documentation now on https://docs.kredeum.tech/

**Comment by CertDigital** [comment]
Thank you. I did figure it out and was able to mint a few things. I did notice that it appears matic tokens have to be placed on the matic mainnet to show up in metamask and be used to mint. Ethereum matic tokens show up under ethereum network but you can't use those to mint. So it appears someone will have to setup custom rbc in metamask to show matic mainnet and tokens in it in order to use the plugin and mint on matic mainnet. Do you see this changing in future version of this project?

Thanks.

Sent via the Samsung Galaxy Note10+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by zapaz** [comment]
> ... So it appears someone will have to setup custom rbc in metamask to show matic mainnet and tokens in it in order to use the plugin and mint on matic mainnet. Do you see this changing in future version of this project? 

yes, it's what I mean by "propose automatic network configuration in Metamask for Polygon",  it will come soon

**Comment by CertDigital** [comment]
Yes. That would be nice. I think the main issue for any new user would be knowing to go to the matic wallet v2 page and transferring ethereum matic tokens into the matic mainnet to work in metamask.

Thanks for getting back to me on all of this.

Sent via the Samsung Galaxy Note10+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by zapaz** [comment]
it's there : automatic configuration and connexion to Polygon on latest version : 

https://github.com/Kredeum/gr9/releases/tag/v0.2.13
